-- 코드를 입력하세요
SELECT i.REST_ID,i.REST_NAME,i.FOOD_TYPE,i.FAVORITES,i.ADDRESS,ROUND(AVG(r.REVIEW_SCORE),2) ravg
FROM REST_INFO i, REST_REVIEW r
WHERE i.REST_ID = r.REST_ID AND SUBSTR(i.ADDRESS,1,2) = '서울'
GROUP BY i.REST_ID,i.REST_NAME,i.FOOD_TYPE,i.FAVORITES,i.ADDRESS
ORDER BY ravg DESC,i.FAVORITES DESC;
