-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,TO_CHAR(DATE_OF_BIRTH,'yyyy-mm-dd') FROM MEMBER_PROFILE 
WHERE GENDER = 'W' AND EXTRACT(MONTH FROM DATE_OF_BIRTH) = '03' AND TLNO IS NOT NULL ORDER BY MEMBER_ID;